version: '3.1'
services:
  music-library-database:
    build: ./database
    image: davidnlagrange/music-library-database:1
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    volumes:
      - db-data:/var/lib/mysql
  music-library-backend:
    build: ./backend
    image: davidnlagrange/music-library-backend:1
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - "music-library-database"
    command: >
      sh -c "flask db upgrade && flask run --host=0.0.0.0"
  music-library-frontend:
    build: ./frontend
    image: davidnlagrange/music-library-frontend:1
    ports:
      - 80:80
    depends_on:
      - "music-library-backend"
volumes:
  db-data:
